# Dockerfile

# ---- Stage 1: Build ----
    FROM node:20-alpine AS builder

    # --- Define ARGumentos para las variables de entorno PÚBLICAS ---
    ARG NEXT_PUBLIC_APPWRITE_ENDPOINT
    ARG NEXT_PUBLIC_APPWRITE_PROJECT_ID
    ARG NEXT_PUBLIC_APPWRITE_DATABASE_ID
    ARG NEXT_PUBLIC_COLLECTION_ID_TESTIMONIALS
    ARG NEXT_PUBLIC_COLLECTION_ID_LOCATIONS
    ARG NEXT_PUBLIC_COLLECTION_ID_SERVICES
    ARG NEXT_PUBLIC_COLLECTION_ID_APPOINTMENTS
    ARG NEXT_PUBLIC_COLLECTION_ID_DOCTORS
    ARG NEXT_PUBLIC_COLLECTION_ID_SPECIALTIES
    ARG NEXT_PUBLIC_COLLECTION_ID_PATIENTINFO
    ARG NEXT_PUBLIC_COLLECTION_ID_AVAILABILITYSLOTS
    ARG NEXT_PUBLIC_COLLECTION_ID_ARTICLES
    ARG NEXT_PUBLIC_ASSETS_BUCKET_ID
    # --- FIN ARG ---
    
    WORKDIR /app
    COPY package*.json ./
    RUN npm ci
    COPY . .
    ENV NODE_ENV production
    
    # --- Expón los ARG como ENV para el proceso de build ---
    ENV NEXT_PUBLIC_APPWRITE_ENDPOINT=$NEXT_PUBLIC_APPWRITE_ENDPOINT
    ENV NEXT_PUBLIC_APPWRITE_PROJECT_ID=$NEXT_PUBLIC_APPWRITE_PROJECT_ID
    ENV NEXT_PUBLIC_APPWRITE_DATABASE_ID=$NEXT_PUBLIC_APPWRITE_DATABASE_ID
    ENV NEXT_PUBLIC_COLLECTION_ID_TESTIMONIALS=$NEXT_PUBLIC_COLLECTION_ID_TESTIMONIALS
    ENV NEXT_PUBLIC_COLLECTION_ID_LOCATIONS=$NEXT_PUBLIC_COLLECTION_ID_LOCATIONS
    ENV NEXT_PUBLIC_COLLECTION_ID_SERVICES=$NEXT_PUBLIC_COLLECTION_ID_SERVICES
    ENV NEXT_PUBLIC_COLLECTION_ID_APPOINTMENTS=$NEXT_PUBLIC_COLLECTION_ID_APPOINTMENTS
    ENV NEXT_PUBLIC_COLLECTION_ID_DOCTORS=$NEXT_PUBLIC_COLLECTION_ID_DOCTORS
    ENV NEXT_PUBLIC_COLLECTION_ID_SPECIALTIES=$NEXT_PUBLIC_COLLECTION_ID_SPECIALTIES
    ENV NEXT_PUBLIC_COLLECTION_ID_PATIENTINFO=$NEXT_PUBLIC_COLLECTION_ID_PATIENTINFO
    ENV NEXT_PUBLIC_COLLECTION_ID_AVAILABILITYSLOTS=$NEXT_PUBLIC_COLLECTION_ID_AVAILABILITYSLOTS
    ENV NEXT_PUBLIC_COLLECTION_ID_ARTICLES=$NEXT_PUBLIC_COLLECTION_ID_ARTICLES
    ENV NEXT_PUBLIC_ASSETS_BUCKET_ID=$NEXT_PUBLIC_ASSETS_BUCKET_ID
    # --- FIN ENV ---
    
    # Ejecuta el build (ahora tendrá acceso a las ENV)
    RUN npm run build
    
    # ---- Stage 2: Production Runner ----
    FROM node:20-alpine AS runner
    WORKDIR /app
    ENV NODE_ENV production
    ENV NEXT_TELEMETRY_DISABLED 1
    RUN addgroup --system --gid 1001 nodejs
    RUN adduser --system --uid 1001 nextjs
    
    # Copia los artefactos necesarios
    COPY --from=builder --chown=nextjs:nodejs /app/public ./public
    COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
    COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
    
    USER nextjs
    EXPOSE 3000
    ENV PORT 3000
    CMD ["node", "server.js"]