# .github/workflows/deploy.yml

name: Build and Push Docker Image to GHCR & Trigger Render Deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}/hospital-web-app

jobs:
  build-and-push-image:
    name: Build Docker Image and Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # --- LÍNEAS DE CACHÉ ELIMINADAS ---
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # --- FIN LÍNEAS ELIMINADAS ---
          build-args: |
            NEXT_PUBLIC_APPWRITE_ENDPOINT=https://cloud.appwrite.io/v1
            NEXT_PUBLIC_APPWRITE_PROJECT_ID=67fe86fc0039b06db267
            NEXT_PUBLIC_APPWRITE_DATABASE_ID=67fe874f00007b6702ed
            NEXT_PUBLIC_COLLECTION_ID_TESTIMONIALS=testimonials
            NEXT_PUBLIC_COLLECTION_ID_LOCATIONS=locations
            NEXT_PUBLIC_COLLECTION_ID_SERVICES=services
            NEXT_PUBLIC_COLLECTION_ID_APPOINTMENTS=appointments
            NEXT_PUBLIC_COLLECTION_ID_DOCTORS=doctors
            NEXT_PUBLIC_COLLECTION_ID_SPECIALTIES=specialties
            NEXT_PUBLIC_COLLECTION_ID_PATIENTINFO=Tpatientinfo
            NEXT_PUBLIC_COLLECTION_ID_AVAILABILITYSLOTS=availabilityslots
            NEXT_PUBLIC_COLLECTION_ID_ARTICLES=articles
            NEXT_PUBLIC_ASSETS_BUCKET_ID=app_files

  trigger-render-deploy:
    name: Trigger Render Deployment
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}